[project]
name = "skillbox-practice"
version = "0.1.0"
description = "Project template for joint Skillbox-SPbSU student practice."
authors = ["Aribaldi <corsypirate@gmail.com>"]
channels = ["nvidia", "pytorch", "conda-forge", "anaconda"]
platforms = ["linux-64", "win-64"]
readme = "README.md"

[dependencies]
python = "==3.11.6"
git = ">=2.42"
hydra-core = ">=1.3"
jupyter = ">=1.0"
matplotlib = ">=3.8"
more-itertools = ">=10.1"
numpy = "1.26.2"
omegaconf = ">=2.3"
plotly = ">=5.18"
polars = ">=0.19"
pyarrow = "*"
pydantic = "2.1.1"
quarto = ">=1.3"
s3fs = ">=2021.7"
scikit-learn = ">=1.3"
toolz = ">=0.12"
tqdm = ">=4.66"
ruff = ">=0.1"
commitizen = ">=2.28"
mypy = ">=1.6"
pre-commit = ">=3.5"
pytorch = "2.1.1.*"
pytorch-cuda = "12.1"
transformers = "4.35.2"
datasets = "2.14.4"
pymorphy3 = "*"
nltk = "*"
pandas = "2.1.4"
imbalanced-learn = "*"
accelerate = "*"
lightning = "2.1.1"
catboost = "*"
tensorboard = ">=2.15.1,<2.16"
tensorboardX = ">=2.6.2.2,<2.6.3"

[pypi-dependencies]
emosent-py = "*"
